// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AVCP</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AVCP
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class indici
    {

        private indiciMetadata metadataField;

        private List<indiciDataset> indiceField;

        public indici()
        {
            this.indiceField = new List<indiciDataset>();
            this.metadataField = new indiciMetadata();
        }

        public indiciMetadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("dataset", IsNullable = false)]
        public List<indiciDataset> indice
        {
            get
            {
                return this.indiceField;
            }
            set
            {
                this.indiceField = value;
            }
        }
    }

    public partial class indiciMetadata
    {
        public indiciMetadata()
        {
            dataPubblicazioneIndice = new AVCPDateTime();
            dataUltimoAggiornamentoIndice = new AVCPDateTime();
        }

        private string titoloField;

        private string abstractField;

        private AVCPDateTime dataPubblicazioneIndiceField;

        private string entePubblicatoreField;

        private AVCPDateTime dataUltimoAggiornamentoIndiceField;

        private int annoRiferimentoField;

        private string urlFileField;

        private string licenzaField;

        public string titolo
        {
            get
            {
                return this.titoloField;
            }
            set
            {
                this.titoloField = value;
            }
        }

        public string @abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        public AVCPDateTime dataPubblicazioneIndice
        {
            get
            {
                return this.dataPubblicazioneIndiceField;
            }
            set
            {
                this.dataPubblicazioneIndiceField = value;
            }
        }

        public string entePubblicatore
        {
            get
            {
                return this.entePubblicatoreField;
            }
            set
            {
                this.entePubblicatoreField = value;
            }
        }

        public AVCPDateTime dataUltimoAggiornamentoIndice
        {
            get
            {
                return this.dataUltimoAggiornamentoIndiceField;
            }
            set
            {
                this.dataUltimoAggiornamentoIndiceField = value;
            }
        }

        public int annoRiferimento
        {
            get
            {
                return this.annoRiferimentoField;
            }
            set
            {
                this.annoRiferimentoField = value;
            }
        }

        public string urlFile
        {
            get
            {
                return this.urlFileField;
            }
            set
            {
                this.urlFileField = value;
            }
        }

        public string licenza
        {
            get
            {
                return this.licenzaField;
            }
            set
            {
                this.licenzaField = value;
            }
        }
    }

    public partial class indiciDataset
    {
        public indiciDataset()
        {
            dataUltimoAggiornamento = new AVCPDateTime();
        }

        private string linkDatasetField;

        private AVCPDateTime dataUltimoAggiornamentoField;

        private string idField;

        public string linkDataset
        {
            get
            {
                return this.linkDatasetField;
            }
            set
            {
                this.linkDatasetField = value;
            }
        }

        public AVCPDateTime dataUltimoAggiornamento
        {
            get
            {
                return this.dataUltimoAggiornamentoField;
            }
            set
            {
                this.dataUltimoAggiornamentoField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
}
