// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AVCP</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AVCP
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public enum sceltaContraenteType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-PROCEDURA APERTA")]
        Item01PROCEDURAAPERTA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02-PROCEDURA RISTRETTA")]
        Item02PROCEDURARISTRETTA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03-PROCEDURA NEGOZIATA PREVIA PUBBLICAZIONE DEL BANDO")]
        Item03PROCEDURANEGOZIATAPREVIAPUBBLICAZIONEDELBANDO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04-PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE DEL BANDO")]
        Item04PROCEDURANEGOZIATASENZAPREVIAPUBBLICAZIONEDELBANDO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05-DIALOGO COMPETITIVO")]
        Item05DIALOGOCOMPETITIVO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06-PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI  GARA ART. 221 D.LGS. 163/2006")]
        Item06PROCEDURANEGOZIATASENZAPREVIAINDIZIONEDIGARAART221DLGS1632006,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07-SISTEMA DINAMICO DI ACQUISIZIONE")]
        Item07SISTEMADINAMICODIACQUISIZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08-AFFIDAMENTO IN ECONOMIA - COTTIMO FIDUCIARIO")]
        Item08AFFIDAMENTOINECONOMIACOTTIMOFIDUCIARIO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14-PROCEDURA SELETTIVA EX ART 238 C.7, D.LGS. 163/2006")]
        Item14PROCEDURASELETTIVAEXART238C7DLGS1632006,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17-AFFIDAMENTO DIRETTO EX ART. 5 DELLA LEGGE N.381/91")]
        Item17AFFIDAMENTODIRETTOEXART5DELLALEGGEN38191,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21-PROCEDURA RISTRETTA DERIVANTE DA AVVISI CON CUI SI INDICE LA GARA")]
        Item21PROCEDURARISTRETTADERIVANTEDAAVVISICONCUISIINDICELAGARA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22-PROCEDURA NEGOZIATA DERIVANTE DA AVVISI CON CUI SI INDICE LA GARA")]
        Item22PROCEDURANEGOZIATADERIVANTEDAAVVISICONCUISIINDICELAGARA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23-AFFIDAMENTO IN ECONOMIA - AFFIDAMENTO DIRETTO")]
        Item23AFFIDAMENTOINECONOMIAAFFIDAMENTODIRETTO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24-AFFIDAMENTO DIRETTO A SOCIETA\' IN HOUSE")]
        Item24AFFIDAMENTODIRETTOASOCIETAINHOUSE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25-AFFIDAMENTO DIRETTO A SOCIETA\' RAGGRUPPATE/CONSORZIATE O CONTROLLATE NELLE CON" +
            "CESSIONI DI LL.PP")]
        Item25AFFIDAMENTODIRETTOASOCIETARAGGRUPPATECONSORZIATEOCONTROLLATENELLECONCESSIONIDILLPP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26-AFFIDAMENTO DIRETTO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE")]
        Item26AFFIDAMENTODIRETTOINADESIONEADACCORDOQUADROCONVENZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-CONFRONTO COMPETITIVO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE")]
        Item27CONFRONTOCOMPETITIVOINADESIONEADACCORDOQUADROCONVENZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28-PROCEDURA AI SENSI DEI REGOLAMENTI DEGLI ORGANI COSTITUZIONALI")]
        Item28PROCEDURAAISENSIDEIREGOLAMENTIDEGLIORGANICOSTITUZIONALI,
    }

    public enum ruoloType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-MANDANTE")]
        Item01MANDANTE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02-MANDATARIA")]
        Item02MANDATARIA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03-ASSOCIATA")]
        Item03ASSOCIATA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04-CAPOGRUPPO")]
        Item04CAPOGRUPPO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05-CONSORZIATA")]
        Item05CONSORZIATA,
    }


    public class AVCPDateTime
    {
        private DateTime date;

        public AVCPDateTime()
        {
            this.date = DateTime.Now;
        }
        public AVCPDateTime(DateTime date)
        {
            this.date = date;
        }

        [XmlText]
        public string Date
        {
            get { return date.ToString("yyyy-MM-dd"); }
            set { date = DateTime.ParseExact(value, "yyyy-MM-dd", null); }
        }



    }
    public class codiceFiscaleType : IdentificativoFiscale
    {
        public codiceFiscaleType() { }
        public codiceFiscaleType(string s)
        {
            this.Value = s;
        }
    }
    public class identificativoFiscaleEstero : IdentificativoFiscale
    {
        public identificativoFiscaleEstero() { }
        public identificativoFiscaleEstero(string s)
        {
            this.Value = s;
        }
    }
    public abstract class IdentificativoFiscale
    {
        private string value;
        [XmlText]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                this.value = value;
            }
        }
    }
}
