// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>AVCP</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AVCP
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

    [XmlRoot(Namespace = "legge190_1_0",
     ElementName = "pubblicazione")]
    public  class pubblicazione
    {
        private pubblicazioneMetadata metadataField;

        private List<pubblicazioneLotto> dataField;

        public pubblicazione()
        {
            this.dataField = new List<pubblicazioneLotto>();
            this.metadataField = new pubblicazioneMetadata();
        }

        [XmlElement(Namespace = "")]
        public pubblicazioneMetadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lotto", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<pubblicazioneLotto> data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    public partial class pubblicazioneMetadata
    {
        public pubblicazioneMetadata()
        {
            dataPubbicazioneDataset = new AVCPDateTime();
            dataUltimoAggiornamentoDataset = new AVCPDateTime();
        }

        private string titoloField;

        private string abstractField;

        private AVCPDateTime dataPubbicazioneDatasetField;

        private string entePubblicatoreField;

        private AVCPDateTime dataUltimoAggiornamentoDatasetField;

        private int annoRiferimentoField;

        private string urlFileField;

        private string licenzaField;

        public string titolo
        {
            get
            {
                return this.titoloField;
            }
            set
            {
                this.titoloField = value;
            }
        }

        public string @abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        public AVCPDateTime dataPubbicazioneDataset
        {
            get
            {
                return this.dataPubbicazioneDatasetField;
            }
            set
            {
                this.dataPubbicazioneDatasetField = value;
            }
        }

        public string entePubblicatore
        {
            get
            {
                return this.entePubblicatoreField;
            }
            set
            {
                this.entePubblicatoreField = value;
            }
        }

        public AVCPDateTime dataUltimoAggiornamentoDataset
        {
            get
            {
                return this.dataUltimoAggiornamentoDatasetField;
            }
            set
            {
                this.dataUltimoAggiornamentoDatasetField = value;
            }
        }

        public int annoRiferimento
        {
            get
            {
                return this.annoRiferimentoField;
            }
            set
            {
                this.annoRiferimentoField = value;
            }
        }

        public string urlFile
        {
            get
            {
                return this.urlFileField;
            }
            set
            {
                this.urlFileField = value;
            }
        }

        public string licenza
        {
            get
            {
                return this.licenzaField;
            }
            set
            {
                this.licenzaField = value;
            }
        }
    }

    public partial class singoloType
    {

        private IdentificativoFiscale itemField;


        private string ragioneSocialeField;

        [System.Xml.Serialization.XmlElementAttribute("codiceFiscale", typeof(codiceFiscaleType))]
        [System.Xml.Serialization.XmlElementAttribute("identificativoFiscaleEstero", typeof(identificativoFiscaleEstero))]
        public IdentificativoFiscale identificativoFiscale
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

  

        public string ragioneSociale
        {
            get
            {
                return this.ragioneSocialeField;
            }
            set
            {
                this.ragioneSocialeField = value;
            }
        }
    }

 
   

    public partial class aggregatoType
    {

        private IdentificativoFiscale itemField;

        private string ragioneSocialeField;

        private ruoloType ruoloField;

        [System.Xml.Serialization.XmlElementAttribute("codiceFiscale", typeof(codiceFiscaleType))]
        [System.Xml.Serialization.XmlElementAttribute("identificativoFiscaleEstero", typeof(identificativoFiscaleEstero))]
        public IdentificativoFiscale identificativoFiscale
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

  

        public string ragioneSociale
        {
            get
            {
                return this.ragioneSocialeField;
            }
            set
            {
                this.ragioneSocialeField = value;
            }
        }

        public ruoloType ruolo
        {
            get
            {
                return this.ruoloField;
            }
            set
            {
                this.ruoloField = value;
            }
        }
    }



    public partial class pubblicazioneLotto
    {

        private string cigField;

        private pubblicazioneLottoStrutturaProponente strutturaProponenteField;

        private string oggettoField;

        private sceltaContraenteType sceltaContraenteField;

        private pubblicazioneLottoPartecipanti partecipantiField;

        private pubblicazioneLottoAggiudicatari aggiudicatariField;

        private decimal importoAggiudicazioneField;

        private pubblicazioneLottoTempiCompletamento tempiCompletamentoField;

        private decimal importoSommeLiquidateField;

        public pubblicazioneLotto()
        {
            this.tempiCompletamentoField = new pubblicazioneLottoTempiCompletamento();
            this.aggiudicatariField = new pubblicazioneLottoAggiudicatari();
            this.partecipantiField = new pubblicazioneLottoPartecipanti();
            this.strutturaProponenteField = new pubblicazioneLottoStrutturaProponente();
        }

        [XmlElement(Namespace = "")]
        public string cig
        {
            get
            {
                return this.cigField;
            }
            set
            {
                this.cigField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public pubblicazioneLottoStrutturaProponente strutturaProponente
        {
            get
            {
                return this.strutturaProponenteField;
            }
            set
            {
                this.strutturaProponenteField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public string oggetto
        {
            get
            {
                return this.oggettoField;
            }
            set
            {
                this.oggettoField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public sceltaContraenteType sceltaContraente
        {
            get
            {
                return this.sceltaContraenteField;
            }
            set
            {
                this.sceltaContraenteField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public pubblicazioneLottoPartecipanti partecipanti
        {
            get
            {
                return this.partecipantiField;
            }
            set
            {
                this.partecipantiField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public pubblicazioneLottoAggiudicatari aggiudicatari
        {
            get
            {
                return this.aggiudicatariField;
            }
            set
            {
                this.aggiudicatariField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public decimal importoAggiudicazione
        {
            get
            {
                return this.importoAggiudicazioneField;
            }
            set
            {
                this.importoAggiudicazioneField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public pubblicazioneLottoTempiCompletamento tempiCompletamento
        {
            get
            {
                return this.tempiCompletamentoField;
            }
            set
            {
                this.tempiCompletamentoField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public decimal importoSommeLiquidate
        {
            get
            {
                return this.importoSommeLiquidateField;
            }
            set
            {
                this.importoSommeLiquidateField = value;
            }
        }
    }

    public partial class pubblicazioneLottoStrutturaProponente
    {

        private string codiceFiscalePropField;

        private string denominazioneField;

        [XmlElement(Namespace = "")]
        public string codiceFiscaleProp
        {
            get
            {
                return this.codiceFiscalePropField;
            }
            set
            {
                this.codiceFiscalePropField = value;
            }
        }

        [XmlElement(Namespace = "")]
        public string denominazione
        {
            get
            {
                return this.denominazioneField;
            }
            set
            {
                this.denominazioneField = value;
            }
        }
    }
    public partial class pubblicazioneLottoRaggruppamento {

        private List<aggregatoType> membriField;

        [XmlElement("membro", Type = typeof(aggregatoType))]
        public List<aggregatoType> Membri
        {
            get
            {
                return this.membriField;
            }
            set
            {
                this.membriField = value;
            }
        }
    }

    public partial class pubblicazioneLottoPartecipanti
    {
        private List<pubblicazioneLottoRaggruppamento> raggruppamentiField;

        private List<singoloType> partecipanteField;

        public pubblicazioneLottoPartecipanti()
        {
        }
        [XmlElement("raggruppamento", Type = typeof(pubblicazioneLottoRaggruppamento))]
        public List<pubblicazioneLottoRaggruppamento> Raggruppamenti
        {
            get { return raggruppamentiField; }
            set { raggruppamentiField = value; }
        }

        [XmlElement(Namespace = "")]
        public List<singoloType> partecipante
        {
            get
            {
                return this.partecipanteField;
            }
            set
            {
                this.partecipanteField = value;
            }
        }
    }

    public partial class pubblicazioneLottoAggiudicatari
    {

        private List<pubblicazioneLottoRaggruppamento> raggruppamentiField;

        private List<singoloType> aggiudicatarioField;

        public pubblicazioneLottoAggiudicatari()
        {
        }

        [XmlElement("raggruppamento", Type = typeof(pubblicazioneLottoRaggruppamento))]
        public List<pubblicazioneLottoRaggruppamento> Raggruppamenti
        {
            get { return raggruppamentiField; }
            set { raggruppamentiField = value; }
        }

        [XmlElement(Namespace = "")]
        public List<singoloType> aggiudicatario
        {
            get
            {
                return this.aggiudicatarioField;
            }
            set
            {
                this.aggiudicatarioField = value;
            }
        }
    }

    public partial class pubblicazioneLottoTempiCompletamento
    {

        private AVCPDateTime dataInizioField;

        private bool dataInizioFieldSpecified;

        private AVCPDateTime dataUltimazioneField;

        private bool dataUltimazioneFieldSpecified;


        [XmlElement(Namespace = "")]
        public AVCPDateTime dataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInizioSpecified
        {
            get
            {
                return this.dataInizioFieldSpecified;
            }
            set
            {
                this.dataInizioFieldSpecified = value;
            }
        }

        [XmlElement(Namespace = "")]
        public AVCPDateTime dataUltimazione
        {
            get
            {
                return this.dataUltimazioneField;
            }
            set
            {
                this.dataUltimazioneField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimazioneSpecified
        {
            get
            {
                return this.dataUltimazioneFieldSpecified;
            }
            set
            {
                this.dataUltimazioneFieldSpecified = value;
            }
        }
    }

}
